%YAML:1.0
---
camera_matrix:
   rows: 3
   cols: 3
   dt: d
   data: [ 572.739, 0., 400., 0., 572.739, 400., 0., 0., 1. ]

distortion_coefficients:
   rows: 1
   cols: 5
   dt: d
   data: [ 0.0, 0.0, 0.0, 0.0, 0.0 ]
