camera:
  - id: 0
    transform: # Transformation matrix for the camera in the base frame
      - [-1.0, 0.0, 0.0, 0.5]  # X-axis is flipped
      - [0.0, 1.0, 0.0, 0.5]   # Y-axis remains the same
      - [0.0, 0.0, -1.0, 1.0]  # Z-axis is flipped
      - [0.0, 0.0, 0.0, 1.0]   # Homogeneous coordinate
