camera:
  - id: 1
    transform: # Transformation matrix for the camera in the base frame
      - [0.0, 0.0, 1.0, -1.2]
      - [0.0, -1.0, 0.0, 0.45]
      - [1.0, 0.0, 0.0, 0.0]
      - [0.0, 0.0, 0.0, 1.0]
  - id: 2
    transform: 
      - [-0.5, 0.7071, 0.5, 0.5]
      - [-0.5, -0.7071, 0.5, 1.0]
      - [-0.7071, 0.0, -0.7071, 0.5]
      - [0.0, 0.0, 0.0, 1.0]
