# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - R0_Yaw
      - R1_Pitch
      - R2_Pitch
      - R3_Yaw
      - R4_Pitch
  gripper_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - IdolGearB
      - RightGripper
      - LeftPivotArm
      - RightPivotArm
      - ServoGearB
      - LeftGripper