controller_manager:
  ros__parameters:
    update_rate: 1000 #Hz
    use_sim_time: true

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints: 
      - R0_Yaw
      - R1_Pitch
      - R2_Pitch
      - R3_Yaw
      - R4_Pitch

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

    allow_partial_joints_goal: true # Defaults to false
    hardware_state_has_offset: true
    deduce_states_from_derivatives: true
    
    constraints:
      stopped_velocity_tolerance: 0.01 # Defaults to 0.01
      goal_time: 0.0 # Defaults to 0.0 (start immediately)
    
    gains:
      R0_Yaw: {p: 100.0, i: 0.01, d: 1.0}
      R1_Pitch: {p: 100.0, i: 0.01, d: 1.0}
      R2_Pitch: {p: 100.0, i: 0.01, d: 1.0}
      R3_Yaw: {p: 100.0, i: 0.01, d: 1.0}
      R4_Pitch: {p: 100.0, i: 0.01, d: 1.0}




