name: Code Quality Linter

# Trigger the workflow on push and pull request events
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # C++ Linter job using cppcheck and clang-format
  lint_cpp:
    name: Lint C++ Code
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Install cppcheck
      - name: Install cppcheck
        run: sudo apt-get install -y cppcheck

      # Run cppcheck on the C++ source directory
      - name: Run cppcheck
        run: cppcheck --enable=all --inconclusive --error-exitcode=1 src/robot_control/src

      # Install clang-format
      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      # Check C++ formatting with clang-format
      - name: Run clang-format
        run: |
          # Find all C++ source files and check formatting
          find src/robot_control/src -name "*.cpp" -o -name "*.h" | xargs clang-format --dry-run --Werror

  # Python Linter job using flake8
  lint_python:
    name: Lint Python Code
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python (with the desired version if needed)
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install flake8 linter
      - name: Install flake8
        run: python -m pip install flake8

      # Run flake8 on the Python source directory
      - name: Run flake8
        run: flake8 src/robot_description/launch

